from h import *
with sync_playwright() as pw:
    p = open_page(pw, "pakiti.html?duka=b1", shop_store("b1", "boutique", "waridi"))
    setup_owner(p)
    p.click(".pk-nav:has-text('Mavazi')"); p.click("text=＋ Mtindo"); p.fill("#sf-n","Gauni la Ankara"); p.fill("#sf-c","Magauni"); p.fill("#sf-p","45000"); p.fill("#sf-k","25000"); p.fill("#sf-s","S, M, L"); p.fill("#sf-r","Nyekundu, Bluu"); p.click(".pk-md >> button:has-text('Hifadhi')"); p.wait_for_timeout(200)
    p.fill("#sq-0-0","2"); p.fill("#sq-0-1","3"); p.fill("#sq-1-2","1"); p.click("text=✅ Ingiza stock"); p.wait_for_timeout(200)
    p.click("text=＋ Mtindo"); p.fill("#sf-n","Viatu Loafers"); p.fill("#sf-c","Viatu"); p.fill("#sf-p","60000"); p.fill("#sf-d","20"); p.click(".pk-md >> .chip:has-text('viatu')"); p.fill("#sf-r","Kahawia"); p.click(".pk-md >> button:has-text('Hifadhi')"); p.wait_for_timeout(200)
    p.fill("#sq-0-3","4"); p.click("text=✅ Ingiza stock"); p.wait_for_timeout(200)
    shot(p,"bt-mavazi"); print(p.inner_text(".kpis"))
    p.click(".pk-nav:has-text('Uza')"); p.click("text=＋ Sajili mteja mpya"); p.fill("#cu-n","Halima"); p.fill("#cu-p","0713000000"); p.click(".pk-md >> button:has-text('Hifadhi')"); p.wait_for_timeout(200)
    p.click(".prod:has-text('Gauni')"); shot(p,"bt-pick"); p.click(".pk-md td >> text=3"); p.click(".prod:has-text('Viatu')"); p.click(".pk-md button:has-text('4')")
    shot(p,"bt-uza"); print(p.inner_text(".card.sticky")[:400])
    p.click("text=💳 Lipa >> nth=0"); p.click("text=✅ Thibitisha"); p.wait_for_timeout(400); print(p.inner_text(".rc")[-200:]); p.click(".pk-md >> text=✕")
    st=store(p); print([v.get("v") for v in st.values() if v.get("t")=="style"]); print([ (v["name"],v.get("points"),v.get("spent")) for v in st.values() if v.get("t")=="cust"])
    p.click(".pk-nav:has-text('Marejesho')"); p.fill("#rt-no","1"); p.click("text=Tafuta"); p.wait_for_timeout(200); p.fill("#rq-0","1"); p.fill("#rt-why","saizi"); p.click("text=Mpe salio"); p.wait_for_timeout(300)
    print(p.inner_text(".card.sticky")[:300])
    st=store(p); print([v.get("v") for v in st.values() if v.get("t")=="style"]); print([ (v["name"],v.get("credit")) for v in st.values() if v.get("t")=="cust"])
    p.click(".pk-nav:has-text('Ripoti')"); p.wait_for_timeout(200); print(p.inner_text(".kpis")); shot(p,"bt-ripoti")
    print("ERRS", p.errs)
