from h import *
with sync_playwright() as pw:
    p = open_page(pw, "pakiti.html?duka=m1", shop_store("m1", "mgahawa", "kitenge"))
    setup_owner(p); shot(p,"mg-empty")
    p.click("button:has-text('Weka menyu')")
    for n,c,pr,stn in [("Pilau nyama","Vyakula",8000,"jikoni"),("Chips kuku","Vyakula",9000,"jikoni"),("Kilimanjaro","Bia",3500,"bar"),("Juisi ya embe","Vinywaji baridi",3000,"bar")]:
        p.click("text=＋ Menyu"); p.fill("#it-n",n); p.fill("#it-c",c); p.fill("#it-p",str(pr)); p.select_option("#it-s",stn); p.click(".pk-md >> text=Hifadhi"); p.wait_for_timeout(120)
    shot(p,"mg-menyu")
    p.click(".pk-nav:has-text('Meza')"); p.click("text=Panga meza"); p.fill("#tb-a","1"); p.fill("#tb-b","8"); p.fill("#tb-ar","Ndani"); p.click(".pk-md >> text=＋ Ongeza"); p.wait_for_timeout(150)
    p.fill("#tb-a","VIP 1"); p.fill("#tb-b",""); p.fill("#tb-ar","Nje"); p.click(".pk-md >> text=＋ Ongeza"); p.wait_for_timeout(150); p.click(".pk-md >> [aria-label=Funga]")
    p.click(".tile:has-text('Wazi') >> nth=2"); p.wait_for_timeout(300)
    p.click(".prod:has-text('Pilau')"); p.click(".prod:has-text('Pilau')"); p.click(".prod:has-text('Kilimanjaro')")
    p.click("text=＋ maelekezo >> nth=0"); p.fill("#dn","bila pilipili"); p.click(".pk-md >> text=Sawa")
    shot(p,"mg-oda")
    p.click("text=🔥 Tuma"); p.wait_for_timeout(600)
    shot(p,"mg-meza"); print(p.inner_text(".kpis"))
    p.click(".pk-nav:has-text('Jikoni')"); p.wait_for_timeout(200); print(p.inner_text(".kan")[:300])
    p.click(".kan >> text=Anza"); p.wait_for_timeout(200); p.click(".kan >> text=Tayari ✓"); p.wait_for_timeout(200)
    p.click(".chip:has-text('Bar')"); p.click(".kan >> text=Anza"); p.wait_for_timeout(200); shot(p,"mg-jikoni")
    p.click(".pk-nav:has-text('Meza')"); p.click(".tile:has-text('Eric')"); p.wait_for_timeout(200)
    p.click("text=🔔 Peleka"); p.wait_for_timeout(200)
    p.click("text=🧾 Bili / Lipa"); p.wait_for_timeout(200); shot(p,"mg-bili")
    p.click(".chip:has-text('÷2')"); print("half", p.input_value("#bl-a")); p.click("text=💵 Pokea malipo"); p.wait_for_timeout(400)
    print(p.inner_text(".pk-md table"))
    p.click(".chip:has-text('M-Pesa')"); p.click("text=💵 Pokea malipo"); p.wait_for_timeout(400)
    print(p.inner_text(".rc")[:300]); p.click(".pk-md >> text=✕")
    # takeaway
    p.click("text=🥡 Take-away"); p.fill("#no-c","Juma"); p.click("text=Anza oda"); p.wait_for_timeout(300); p.click(".prod:has-text('Chips')"); p.click("text=🔥 Tuma"); p.wait_for_timeout(500)
    print(p.inner_text(".pk-page")[:400])
    p.click(".pk-nav:has-text('Ripoti')"); p.wait_for_timeout(200); print(p.inner_text(".kpis")); shot(p,"mg-ripoti")
    p.set_viewport_size({"width":390,"height":800}); p.click(".pk-bot >> text=Meza"); p.wait_for_timeout(200); shot(p,"mg-mobile")
    print("ERRS", p.errs)
